# -*- mode: python ; coding: utf-8 -*-

block_cipher = None


a = Analysis(['gui.py'],
             pathex=['/home/labcaron/Projects/MhcVizPipe/MhcVizPipe'],
             binaries=[],
             datas=[('/home/labcaron/Projects/MhcVizPipe/venv/lib/python3.7/site-packages/plotly', 'plotly'),
                    ('/home/labcaron/Projects/MhcVizPipe/venv/lib/python3.7/site-packages/dominate', 'dominate'),
                    ('/home/labcaron/Projects/MhcVizPipe/venv/lib/python3.7/site-packages/dash', 'dash'),
                    ('/home/labcaron/Projects/MhcVizPipe/venv/lib/python3.7/site-packages/dash_renderer',
                     'dash_renderer'),
                    ('/home/labcaron/Projects/MhcVizPipe/venv/lib/python3.7/site-packages/dash_core_components',
                     'dash_core_components'),
                    ('/home/labcaron/Projects/MhcVizPipe/venv/lib/python3.7/site-packages/dash_html_components',
                     'dash_html_components'),
                    ('/home/labcaron/Projects/MhcVizPipe/venv/lib/python3.7/site-packages/dash_bootstrap_components',
                     'dash_bootstrap_components'),
                    ('/home/labcaron/Projects/MhcVizPipe/venv/lib/python3.7/site-packages/PlotlyLogo', 'PlotlyLogo'),
                    ('/home/labcaron/Projects/MhcVizPipe/venv/lib/python3.7/site-packages/MhcVizPipe', 'MhcVizPipe'),
                    ('/home/labcaron/Projects/MhcVizPipe/venv/lib/python3.7/site-packages/waitress', 'waitress'),
                    ('/home/labcaron/Projects/MhcVizPipe/venv/lib/python3.7/site-packages/flask', 'flask'),
                    ('/home/labcaron/Projects/MhcVizPipe/venv/lib/python3.7/site-packages/seaborn', 'seaborn'),
                    ('/home/labcaron/Projects/MhcVizPipe/venv/lib/python3.7/site-packages/six.py', 'six'),
                    (
                    '/home/labcaron/Projects/MhcVizPipe/venv/lib/python3.7/site-packages/pkg_resources/_vendor/appdirs.py',
                    'appdirs')],
             hiddenimports=[],
             hookspath=[],
             runtime_hooks=[],
             excludes=[],
             win_no_prefer_redirects=False,
             win_private_assemblies=False,
             cipher=block_cipher,
             noarchive=False)
pyz = PYZ(a.pure, a.zipped_data,
             cipher=block_cipher)
exe = EXE(pyz,
          a.scripts,
          a.binaries,
          a.zipfiles,
          a.datas,
          [],
          name='gui',
          debug=False,
          bootloader_ignore_signals=False,
          strip=False,
          upx=True,
          upx_exclude=[],
          runtime_tmpdir=None,
          console=True )
